import { useEffect, useState } from 'react'
import { ActivityIndicator, Pressable, ScrollView, Text, TextInput, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { api, request } from '../../services/api'
import type { EventItem, EventTemplate } from '../../types/events'
import { colors, styles } from '../../theme/styles'

const tomorrow = new Date(Date.now() + 86400000).toISOString().slice(0, 16)
export function CreateEventScreen({ navigation }: { navigation: any }) {
  const [name, setName] = useState(''); const [type, setType] = useState('CUSTOM'); const [description, setDescription] = useState(''); const [startsAt, setStartsAt] = useState(tomorrow); const [location, setLocation] = useState(''); const [capacity, setCapacity] = useState(''); const [template, setTemplate] = useState(''); const [templates, setTemplates] = useState<EventTemplate[]>([]); const [error, setError] = useState(''); const [loading, setLoading] = useState(false)
  useEffect(() => { api<EventTemplate[]>('/modules/templates').then(setTemplates).catch(() => setTemplates([])) }, [])
  async function submit() { const date = new Date(startsAt); if (!name.trim() || Number.isNaN(date.getTime())) return setError('Ingresa nombre y fecha válida en formato YYYY-MM-DDTHH:mm.'); setLoading(true); setError(''); try { const event = await request<EventItem>('/events', 'POST', { name: name.trim(), type: type.trim().toUpperCase(), description: description.trim() || null, startsAt: date.toISOString(), endsAt: null, location: location.trim() || null, estimatedCapacity: Number(capacity) || 0, budget: null, templateCode: template || null }); navigation.replace('Inicio del evento', { event }) } catch (reason) { setError((reason as Error).message) } finally { setLoading(false) } }
  return <SafeAreaView style={styles.authScreen}><ScrollView contentContainerStyle={styles.scrollScreen} keyboardShouldPersistTaps="handled"><Text style={styles.kicker}>NUEVO PROYECTO</Text><Text style={styles.title}>Crea tu evento</Text><TextInput style={styles.input} placeholder="Nombre del evento" value={name} onChangeText={setName} /><TextInput style={styles.input} placeholder="Tipo: CONFERENCE, WEDDING, CUSTOM…" value={type} onChangeText={setType} autoCapitalize="characters" /><TextInput style={[styles.input, styles.textArea]} placeholder="Descripción" value={description} onChangeText={setDescription} multiline /><Text style={styles.label}>Inicio (YYYY-MM-DDTHH:mm)</Text><TextInput style={styles.input} value={startsAt} onChangeText={setStartsAt} autoCapitalize="none" /><TextInput style={styles.input} placeholder="Ubicación" value={location} onChangeText={setLocation} /><TextInput style={styles.input} placeholder="Capacidad estimada" value={capacity} onChangeText={setCapacity} keyboardType="number-pad" />
    {!!templates.length && <><Text style={styles.section}>Plantilla sugerida</Text><View style={styles.rowWrap}>{templates.map(item => <Pressable key={item.code} style={[styles.choice, template === item.code && styles.choiceSelected]} onPress={() => { setTemplate(item.code); setType(item.code) }}><Text style={styles.choiceText}>{item.name}</Text></Pressable>)}</View></>}
    {!!error && <Text style={styles.error}>{error}</Text>}<Pressable style={[styles.button, loading && styles.buttonDisabled]} disabled={loading} onPress={submit}>{loading ? <ActivityIndicator color={colors.white} /> : <Text style={styles.buttonText}>Crear evento</Text>}</Pressable></ScrollView></SafeAreaView>
}
