import { useCallback, useState } from 'react'
import { ActivityIndicator, FlatList, Pressable, Text, View } from 'react-native'
import { useFocusEffect } from '@react-navigation/native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { api, request } from '../../services/api'
import type { EventItem, EventModule, ModuleCatalogItem } from '../../types/events'
import { colors, styles } from '../../theme/styles'

export function ModuleManagementScreen({ route }: { route: any }) {
  const event: EventItem = route.params.event; const [catalog, setCatalog] = useState<ModuleCatalogItem[]>([]); const [configured, setConfigured] = useState<EventModule[]>([]); const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(''); const [error, setError] = useState('')
  const load = useCallback(async () => { setLoading(true); setError(''); try { const [all, current] = await Promise.all([api<ModuleCatalogItem[]>('/modules'), api<EventModule[]>(`/events/${event.id}/modules`)]); setCatalog(all); setConfigured(current) } catch (reason) { setError((reason as Error).message) } finally { setLoading(false) } }, [event.id])
  useFocusEffect(useCallback(() => { load() }, [load]))
  async function toggle(item: ModuleCatalogItem) { const current = configured.find(value => value.code === item.code); setBusy(item.code); setError(''); try { if (!current) await request(`/events/${event.id}/modules/${item.code}`, 'POST'); else await request(`/events/${event.id}/modules/${item.code}`, 'PUT', { enabled: !current.enabled, featured: current.featured, audience: current.audience ?? 'ALL', configuration: current.configuration ?? '{}' }); await load() } catch (reason) { setError((reason as Error).message) } finally { setBusy('') } }
  async function feature(current: EventModule) { setBusy(current.code); setError(''); try { await request(`/events/${event.id}/modules/${current.code}`, 'PUT', { enabled: true, featured: !current.featured, audience: current.audience ?? 'ALL', configuration: current.configuration ?? '{}' }); await load() } catch (reason) { setError((reason as Error).message) } finally { setBusy('') } }
  return <SafeAreaView style={styles.screen}><Text style={styles.kicker}>{event.name}</Text><Text style={styles.heading}>Módulos</Text><Text style={styles.muted}>Activa la experiencia y elige los accesos destacados.</Text>{!!error && <Text style={styles.error}>{error}</Text>}{loading ? <ActivityIndicator color={colors.coral} /> : <FlatList style={{ marginTop: 20 }} data={catalog.filter(item => item.available)} keyExtractor={item => item.code} contentContainerStyle={styles.list} renderItem={({ item }) => { const current = configured.find(value => value.code === item.code); const enabled = current?.enabled ?? false; return <View style={styles.card}><View style={styles.row}><View style={styles.moduleBody}><Text style={styles.moduleTitle}>{item.name}</Text><Text style={styles.muted}>{item.category} · {item.code}</Text></View><Text style={enabled ? styles.notice : styles.statusPill}>{enabled ? 'Activo' : 'Inactivo'}</Text></View><Text style={styles.muted}>{item.description}</Text><View style={styles.rowWrap}><Pressable disabled={busy === item.code} style={styles.secondaryButton} onPress={() => toggle(item)}><Text style={styles.secondaryButtonText}>{enabled ? 'Desactivar' : 'Activar'}</Text></Pressable>{enabled && current && <Pressable disabled={busy === item.code} style={[styles.secondaryButton, current.featured && styles.choiceSelected]} onPress={() => feature(current)}><Text style={styles.secondaryButtonText}>{current.featured ? 'Quitar destacado' : 'Destacar'}</Text></Pressable>}</View></View> }} />}</SafeAreaView>
}
