import { StyleSheet } from 'react-native'

export const colors = {
  navy: '#10213a', ink: '#253044', coral: '#f56642', cream: '#f5f1e9', white: '#ffffff',
  muted: '#697386', border: '#d8d4cb', success: '#287846', danger: '#ae4139', softCoral: '#fff0ea',
}

export const styles = StyleSheet.create({
  loading: { flex: 1, justifyContent: 'center', backgroundColor: colors.cream },
  authScreen: { flex: 1, backgroundColor: colors.cream },
  authScroll: { flexGrow: 1, justifyContent: 'center', paddingVertical: 40, paddingHorizontal: 24 },
  authContent: { width: '100%', maxWidth: 440, alignSelf: 'center' },
  screen: { flex: 1, padding: 22, backgroundColor: colors.cream },
  scrollScreen: { flexGrow: 1, padding: 22, paddingBottom: 48, backgroundColor: colors.cream },
  logoRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 34 },
  logo: { width: 38, height: 38 },
  brand: { fontSize: 23, fontWeight: '800', color: colors.navy, letterSpacing: -1 },
  title: { fontSize: 38, lineHeight: 41, fontWeight: '700', color: colors.navy, marginBottom: 12, letterSpacing: -1.3 },
  heading: { fontSize: 34, fontWeight: '700', color: colors.navy, letterSpacing: -1.2 },
  muted: { color: colors.muted, fontSize: 15, lineHeight: 22 },
  input: { width: '100%', backgroundColor: colors.white, borderWidth: 1, borderColor: '#cbc6bb', borderRadius: 8, padding: 15, marginTop: 14, fontSize: 16, color: colors.ink },
  textArea: { minHeight: 96, textAlignVertical: 'top' },
  button: { width: '100%', backgroundColor: colors.navy, padding: 16, borderRadius: 8, alignItems: 'center', marginTop: 20 },
  buttonDisabled: { opacity: 0.55 },
  buttonText: { color: colors.white, fontWeight: '700', fontSize: 16 },
  secondaryButton: { borderWidth: 1, borderColor: colors.navy, padding: 13, borderRadius: 8, alignItems: 'center', marginTop: 12 },
  secondaryButtonText: { color: colors.navy, fontWeight: '700' },
  dangerButton: { borderWidth: 1, borderColor: colors.danger, padding: 13, borderRadius: 8, alignItems: 'center', marginTop: 20 },
  dangerButtonText: { color: colors.danger, fontWeight: '700' },
  centerLink: { color: colors.navy, fontWeight: '700', textAlign: 'center', marginTop: 16, fontSize: 14 },
  loginLinks: { width: '100%', flexDirection: 'row', justifyContent: 'space-between', gap: 16, flexWrap: 'wrap' },
  notice: { color: colors.success, backgroundColor: '#e8f8ee', padding: 12, borderRadius: 8, marginTop: 12 },
  demoNote: { color: '#9a5a2d', backgroundColor: '#fff3df', padding: 10, borderRadius: 8, marginTop: 12, fontSize: 12 },
  error: { color: colors.danger, backgroundColor: '#fff0ee', padding: 12, borderRadius: 8, marginTop: 12 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 22, gap: 12 },
  rowWrap: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 10 },
  link: { color: colors.coral, fontWeight: '700' },
  kicker: { fontSize: 11, letterSpacing: 2, color: colors.coral, fontWeight: '800', marginBottom: 8 },
  list: { gap: 10, paddingBottom: 48 },
  card: { backgroundColor: colors.white, padding: 20, borderRadius: 10, borderWidth: 1, borderColor: colors.border },
  cardTitle: { fontSize: 20, fontWeight: '700', color: '#202b3b', marginVertical: 9 },
  pill: { alignSelf: 'flex-start', fontSize: 10, color: '#c24a2f', backgroundColor: colors.softCoral, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4, fontWeight: '800' },
  statusPill: { alignSelf: 'flex-start', fontSize: 10, color: colors.navy, backgroundColor: '#e7edf6', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4, fontWeight: '800' },
  section: { fontSize: 19, fontWeight: '800', color: colors.ink, marginTop: 28, marginBottom: 14 },
  featured: { flexDirection: 'row', gap: 10, flexWrap: 'wrap' },
  feature: { width: '31%', backgroundColor: colors.navy, padding: 14, borderRadius: 8, minHeight: 100, justifyContent: 'space-between' },
  icon: { color: '#dfe3ff', fontWeight: '800' },
  featureText: { color: colors.white, fontWeight: '700' },
  module: { flexDirection: 'row', alignItems: 'center', gap: 13, backgroundColor: colors.white, padding: 14, borderRadius: 8, marginBottom: 10, borderWidth: 1, borderColor: colors.border },
  moduleIcon: { width: 44, height: 44, borderRadius: 6, backgroundColor: colors.softCoral, alignItems: 'center', justifyContent: 'center' },
  moduleCode: { fontWeight: '800', color: '#c24a2f', fontSize: 12 },
  moduleTitle: { fontSize: 16, fontWeight: '700', color: '#273246' },
  moduleBody: { flex: 1 },
  chevron: { marginLeft: 'auto', fontSize: 28, color: '#a0a7b4' },
  fab: { position: 'absolute', right: 22, bottom: 24, backgroundColor: colors.coral, width: 58, height: 58, borderRadius: 29, alignItems: 'center', justifyContent: 'center' },
  fabText: { color: colors.white, fontSize: 30, lineHeight: 32 },
  label: { color: colors.ink, fontWeight: '700', marginTop: 18, marginBottom: -6 },
  choice: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, paddingVertical: 10, paddingHorizontal: 12, borderRadius: 8 },
  choiceSelected: { borderColor: colors.coral, backgroundColor: colors.softCoral },
  choiceText: { color: colors.ink, fontWeight: '600' },
  divider: { height: 1, backgroundColor: colors.border, marginVertical: 24 },
  switchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 11 },
})
