import { StyleSheet } from 'react-native'

export const colors = {
  navy: '#10213a', ink: '#253044', coral: '#f56642', cream: '#f5f1e9', white: '#ffffff',
  muted: '#697386', border: '#d8d4cb', success: '#287846', danger: '#ae4139', softCoral: '#fff0ea',
}

export const styles = StyleSheet.create({
  loading: { flex: 1, justifyContent: 'center', backgroundColor: colors.cream },
  authScreen: { flex: 1, backgroundColor: colors.cream },
  authScroll: { flexGrow: 1, justifyContent: 'center', paddingVertical: 40, paddingHorizontal: 24 },
  authContent: { width: '100%', maxWidth: 440, alignSelf: 'center' },
  screen: { flex: 1, padding: 22, backgroundColor: colors.cream },
  scrollScreen: { flexGrow: 1, padding: 22, paddingBottom: 48, backgroundColor: colors.cream },
  logoRow: { flexDirection: 'row', alignItems: 'center', gap: 10, marginBottom: 34 },
  logo: { width: 38, height: 38 },
  brand: { fontSize: 23, fontWeight: '800', color: colors.navy, letterSpacing: -1 },
  title: { fontSize: 38, lineHeight: 41, fontWeight: '700', color: colors.navy, marginBottom: 12, letterSpacing: -1.3 },
  heading: { fontSize: 34, fontWeight: '700', color: colors.navy, letterSpacing: -1.2 },
  muted: { color: colors.muted, fontSize: 15, lineHeight: 22 },
  input: { width: '100%', backgroundColor: colors.white, borderWidth: 1, borderColor: '#cbc6bb', borderRadius: 8, padding: 15, marginTop: 14, fontSize: 16, color: colors.ink },
  textArea: { minHeight: 96, textAlignVertical: 'top' },
  button: { width: '100%', backgroundColor: colors.navy, padding: 16, borderRadius: 8, alignItems: 'center', marginTop: 20 },
  buttonDisabled: { opacity: 0.55 },
  buttonText: { color: colors.white, fontWeight: '700', fontSize: 16 },
  secondaryButton: { borderWidth: 1, borderColor: colors.navy, padding: 13, borderRadius: 8, alignItems: 'center', marginTop: 12 },
  secondaryButtonText: { color: colors.navy, fontWeight: '700' },
  dangerButton: { borderWidth: 1, borderColor: colors.danger, padding: 13, borderRadius: 8, alignItems: 'center', marginTop: 20 },
  dangerButtonText: { color: colors.danger, fontWeight: '700' },
  centerLink: { color: colors.navy, fontWeight: '700', textAlign: 'center', marginTop: 16, fontSize: 14 },
  loginLinks: { width: '100%', flexDirection: 'row', justifyContent: 'space-between', gap: 16, flexWrap: 'wrap' },
  notice: { color: colors.success, backgroundColor: '#e8f8ee', padding: 12, borderRadius: 8, marginTop: 12 },
  demoNote: { color: '#9a5a2d', backgroundColor: '#fff3df', padding: 10, borderRadius: 8, marginTop: 12, fontSize: 12 },
  error: { color: colors.danger, backgroundColor: '#fff0ee', padding: 12, borderRadius: 8, marginTop: 12 },
  row: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 22, gap: 12 },
  rowWrap: { flexDirection: 'row', alignItems: 'center', flexWrap: 'wrap', gap: 10 },
  link: { color: colors.coral, fontWeight: '700' },
  kicker: { fontSize: 11, letterSpacing: 2, color: colors.coral, fontWeight: '800', marginBottom: 8 },
  list: { gap: 10, paddingBottom: 48 },
  card: { backgroundColor: colors.white, padding: 20, borderRadius: 10, borderWidth: 1, borderColor: colors.border },
  cardTitle: { fontSize: 20, fontWeight: '700', color: '#202b3b', marginVertical: 9 },
  pill: { alignSelf: 'flex-start', fontSize: 10, color: '#c24a2f', backgroundColor: colors.softCoral, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4, fontWeight: '800' },
  statusPill: { alignSelf: 'flex-start', fontSize: 10, color: colors.navy, backgroundColor: '#e7edf6', paddingHorizontal: 8, paddingVertical: 4, borderRadius: 4, fontWeight: '800' },
  section: { fontSize: 19, fontWeight: '800', color: colors.ink, marginTop: 28, marginBottom: 14 },
  featured: { flexDirection: 'row', gap: 10, flexWrap: 'wrap' },
  feature: { width: '31%', backgroundColor: colors.navy, padding: 14, borderRadius: 8, minHeight: 100, justifyContent: 'space-between' },
  icon: { color: '#dfe3ff', fontWeight: '800' },
  featureText: { color: colors.white, fontWeight: '700' },
  module: { flexDirection: 'row', alignItems: 'center', gap: 13, backgroundColor: colors.white, padding: 14, borderRadius: 8, marginBottom: 10, borderWidth: 1, borderColor: colors.border },
  moduleIcon: { width: 44, height: 44, borderRadius: 6, backgroundColor: colors.softCoral, alignItems: 'center', justifyContent: 'center' },
  moduleCode: { fontWeight: '800', color: '#c24a2f', fontSize: 12 },
  moduleTitle: { fontSize: 16, fontWeight: '700', color: '#273246' },
  moduleBody: { flex: 1 },
  chevron: { marginLeft: 'auto', fontSize: 28, color: '#a0a7b4' },
  fab: { position: 'absolute', right: 22, bottom: 24, backgroundColor: colors.coral, width: 58, height: 58, borderRadius: 29, alignItems: 'center', justifyContent: 'center' },
  fabText: { color: colors.white, fontSize: 30, lineHeight: 32 },
  label: { color: colors.ink, fontWeight: '700', marginTop: 18, marginBottom: -6 },
  choice: { borderWidth: 1, borderColor: colors.border, backgroundColor: colors.white, paddingVertical: 10, paddingHorizontal: 12, borderRadius: 8 },
  choiceSelected: { borderColor: colors.coral, backgroundColor: colors.softCoral },
  choiceText: { color: colors.ink, fontWeight: '600' },
  divider: { height: 1, backgroundColor: colors.border, marginVertical: 24 },
  switchRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 11 },
  guestAccess: { flex: 1, width: '100%', maxWidth: 500, alignSelf: 'center', justifyContent: 'center', padding: 28 },
  guestHome: { flexGrow: 1, paddingBottom: 48, backgroundColor: colors.cream },
  hero: { backgroundColor: colors.navy, paddingTop: 72, paddingHorizontal: 24, paddingBottom: 32, borderBottomLeftRadius: 28, borderBottomRightRadius: 28 },
  heroKicker: { color: '#ffad91', fontWeight: '800', letterSpacing: 1.6, fontSize: 11, marginBottom: 10 },
  heroTitle: { color: colors.white, fontWeight: '800', fontSize: 34, lineHeight: 39, letterSpacing: -1 },
  heroDate: { color: '#eef2f8', fontSize: 15, marginTop: 15, textTransform: 'capitalize' },
  heroLocation: { color: '#b9c5d7', fontSize: 14, marginTop: 6 },
  heroPill: { alignSelf: 'flex-start', color: colors.white, backgroundColor: '#344963', overflow: 'hidden', paddingHorizontal: 10, paddingVertical: 6, borderRadius: 5, fontSize: 10, fontWeight: '800', marginTop: 20 },
  liveCard: { marginHorizontal: 22, marginTop: -1, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 18 },
  guestGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 12, paddingHorizontal: 22 },
  guestModule: { width: '48%', minHeight: 150, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, borderRadius: 12, padding: 16 },
  guestModuleFeatured: { backgroundColor: colors.navy, borderColor: colors.navy },
  guestModuleCodeFeatured: { color: '#ffad91' },
  guestModuleTextFeatured: { color: colors.white },
  guestModuleDescriptionFeatured: { color: '#b9c5d7' },
  moduleDescription: { color: colors.muted, lineHeight: 19, marginTop: 6, fontSize: 13 },
  rsvpRow: { flexDirection: 'row', gap: 10, marginTop: 26 },
  rsvpChoice: { flex: 1, backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, padding: 18, borderRadius: 10 },
  rsvpChoiceSelected: { borderWidth: 2, borderColor: colors.coral, backgroundColor: colors.softCoral },
  rsvpChoiceTitle: { color: colors.navy, fontWeight: '800', textAlign: 'center' },
  passScreen: { flexGrow: 1, padding: 22, paddingBottom: 48, alignItems: 'stretch', backgroundColor: colors.cream },
  passCard: { backgroundColor: colors.white, borderRadius: 16, borderWidth: 1, borderColor: colors.border, padding: 24, marginTop: 22, alignItems: 'center' },
  passEvent: { color: colors.navy, fontWeight: '800', fontSize: 22, textAlign: 'center', marginBottom: 4 },
  qrWrap: { padding: 18, borderWidth: 1, borderColor: colors.border, borderRadius: 12, marginVertical: 24 },
  passName: { fontSize: 24, fontWeight: '800', color: colors.navy, textAlign: 'center', marginBottom: 10 },
  passDetails: { width: '100%', flexDirection: 'row', justifyContent: 'space-around', borderTopWidth: 1, borderTopColor: colors.border, marginTop: 22, paddingTop: 18 },
  detailLabel: { color: colors.muted, fontSize: 10, fontWeight: '800', textAlign: 'center' },
  detailValue: { color: colors.navy, fontSize: 18, fontWeight: '800', textAlign: 'center', marginTop: 5 },
  passAssignment: { color: colors.navy, fontWeight: '700', marginTop: 18 },
  passHint: { color: colors.muted, fontSize: 13, lineHeight: 20, textAlign: 'center', margin: 18 },
  timeline: { marginTop: 28 },
  timelineItem: { flexDirection: 'row', gap: 16, paddingVertical: 18, borderBottomWidth: 1, borderBottomColor: colors.border },
  timelineItemActive: { backgroundColor: colors.softCoral, borderRadius: 10, paddingHorizontal: 12 },
  timelineTime: { width: 72, color: colors.coral, fontWeight: '800', fontSize: 15 },
  timelineBody: { flex: 1, gap: 5 },
  timelineZone: { color: colors.navy, fontWeight: '700', marginTop: 6 },
  noticeList: { gap: 12, marginTop: 24 },
  noticeDate: { color: colors.coral, fontWeight: '800', fontSize: 11, textTransform: 'capitalize' },
  categoryList: { gap: 9 },
  successScreen: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 36, backgroundColor: colors.cream, gap: 16 },
  successMark: { width: 72, height: 72, borderRadius: 36, backgroundColor: '#e8f8ee', color: colors.success, fontSize: 42, textAlign: 'center', lineHeight: 70, overflow: 'hidden' },
  assignmentCard: { backgroundColor: colors.navy, padding: 22, borderRadius: 12, marginTop: 24 },
  assignmentTitle: { color: colors.white, fontSize: 24, fontWeight: '800' },
  mapPoint: { flexDirection: 'row', alignItems: 'center', gap: 14, backgroundColor: colors.white, borderRadius: 10, borderWidth: 1, borderColor: colors.border, padding: 15 },
  mapPin: { width: 44, height: 44, borderRadius: 22, backgroundColor: colors.softCoral, alignItems: 'center', justifyContent: 'center' },
  mapPinText: { color: colors.coral, fontSize: 23, fontWeight: '800' },
  eventsScreen: { flexGrow: 1, padding: 22, paddingTop: 68, paddingBottom: 48, backgroundColor: colors.cream },
  eventsHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', gap: 16 },
  addEventButton: { width: 48, height: 48, borderRadius: 24, backgroundColor: colors.navy, alignItems: 'center', justifyContent: 'center' },
  addEventText: { color: colors.white, fontSize: 28, lineHeight: 31 },
  eventCards: { gap: 14, marginTop: 26 },
  eventCard: { backgroundColor: colors.navy, padding: 22, borderRadius: 14, minHeight: 210 },
  eventCardType: { color: '#ffad91', fontSize: 11, letterSpacing: 1.5, fontWeight: '800' },
  eventCardTitle: { color: colors.white, fontSize: 27, lineHeight: 31, fontWeight: '800', marginTop: 12 },
  eventCardDate: { color: '#eef2f8', fontSize: 14, marginTop: 14, marginBottom: 5, textTransform: 'capitalize' },
  eventCardFooter: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', borderTopWidth: 1, borderTopColor: '#344963', marginTop: 22, paddingTop: 15 },
  eventCardGuest: { color: colors.white, fontWeight: '700' },
  removeEventText: { color: colors.coral, fontWeight: '800', fontSize: 12 },
  emptyEvents: { backgroundColor: colors.white, borderWidth: 1, borderColor: colors.border, padding: 24, borderRadius: 12, marginTop: 28 },
})
