import { useEffect, useState } from 'react'
import { ActivityIndicator, Alert, Pressable, ScrollView, Switch, Text, TextInput, View } from 'react-native'
import { SafeAreaView } from 'react-native-safe-area-context'
import { api, logout, request } from '../../services/api'
import type { UserProfile } from '../../types/events'
import { colors, styles } from '../../theme/styles'

export function ProfileScreen({ navigation }: { navigation: any }) {
  const [profile, setProfile] = useState<UserProfile | null>(null); const [name, setName] = useState(''); const [phone, setPhone] = useState(''); const [preferences, setPreferences] = useState({ email: true, push: true, inApp: true }); const [currentPassword, setCurrentPassword] = useState(''); const [newPassword, setNewPassword] = useState(''); const [message, setMessage] = useState(''); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [saving, setSaving] = useState(false)
  useEffect(() => { api<UserProfile>('/users/me').then(value => { setProfile(value); setName(value.name); setPhone(value.phone ?? ''); if (value.preferences) setPreferences(value.preferences) }).catch(reason => setError(reason.message)).finally(() => setLoading(false)) }, [])
  async function save() { setSaving(true); setError(''); setMessage(''); try { const updated = await request<UserProfile>('/users/me', 'PUT', { name: name.trim(), phone: phone.trim() }); await request('/users/me/preferences', 'PUT', preferences); setProfile(updated); setMessage('Perfil actualizado.') } catch (reason) { setError((reason as Error).message) } finally { setSaving(false) } }
  async function changePassword() { if (!currentPassword || !newPassword) return setError('Completa ambas contraseñas.'); setSaving(true); setError(''); try { await request('/auth/change-password', 'POST', { currentPassword, newPassword, logoutAll: false }); setCurrentPassword(''); setNewPassword(''); setMessage('Contraseña actualizada.') } catch (reason) { setError((reason as Error).message) } finally { setSaving(false) } }
  async function deactivate() { setSaving(true); setError(''); try { await request('/users/me/deactivate', 'POST'); await logout(); navigation.reset({ index: 0, routes: [{ name: 'Login' }] }) } catch (reason) { setError((reason as Error).message); setSaving(false) } }
  function confirmDeactivation() { Alert.alert('Desactivar cuenta', 'No podrás iniciar sesión hasta que un administrador reactive tu cuenta.', [{ text: 'Cancelar', style: 'cancel' }, { text: 'Desactivar', style: 'destructive', onPress: deactivate }]) }
  if (loading) return <SafeAreaView style={styles.loading}><ActivityIndicator color={colors.coral} /></SafeAreaView>
  return <SafeAreaView style={styles.authScreen}><ScrollView contentContainerStyle={styles.scrollScreen} keyboardShouldPersistTaps="handled"><Text style={styles.kicker}>{profile?.status || 'MI CUENTA'}</Text><Text style={styles.heading}>{profile?.name}</Text><Text style={styles.muted}>{profile?.email}</Text><View style={[styles.rowWrap, { marginTop: 10 }]}>{profile?.roles?.map(role => <Text key={role} style={styles.statusPill}>{role}</Text>)}</View><Text style={styles.section}>Datos personales</Text><TextInput style={styles.input} value={name} onChangeText={setName} placeholder="Nombre" /><TextInput style={styles.input} value={phone} onChangeText={setPhone} placeholder="Teléfono" keyboardType="phone-pad" /><Text style={styles.section}>Notificaciones</Text>{(['email', 'push', 'inApp'] as const).map(key => <View style={styles.switchRow} key={key}><Text style={styles.moduleTitle}>{key === 'inApp' ? 'Dentro de la app' : key === 'push' ? 'Push' : 'Correo'}</Text><Switch value={preferences[key]} onValueChange={value => setPreferences(current => ({ ...current, [key]: value }))} /></View>)}{!!error && <Text style={styles.error}>{error}</Text>}{!!message && <Text style={styles.notice}>{message}</Text>}<Pressable style={[styles.button, saving && styles.buttonDisabled]} disabled={saving} onPress={save}><Text style={styles.buttonText}>Guardar perfil</Text></Pressable><View style={styles.divider} /><Text style={styles.section}>Seguridad</Text><TextInput style={styles.input} value={currentPassword} onChangeText={setCurrentPassword} placeholder="Contraseña actual" secureTextEntry /><TextInput style={styles.input} value={newPassword} onChangeText={setNewPassword} placeholder="Nueva contraseña" secureTextEntry /><Pressable style={styles.secondaryButton} disabled={saving} onPress={changePassword}><Text style={styles.secondaryButtonText}>Cambiar contraseña</Text></Pressable><Pressable style={styles.dangerButton} disabled={saving} onPress={confirmDeactivation}><Text style={styles.dangerButtonText}>Desactivar cuenta</Text></Pressable></ScrollView></SafeAreaView>
}
